name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 64.227.143.1
          username: root
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls -ltr
